services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: titly-client 
    ports:
      - "4173:4173"
    depends_on:
      - server
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: titly-server
    ports:
      - "4000:4000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis:6379
    networks:
      - app-network

  redis:
    image: "redis:latest"
    container_name: my-redis-db
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
