services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: titly-client
    ports:
      - "4173:4173"
    depends_on:
      - server
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: titly-server
    ports:
      - "4000:4000"
    depends_on:
      - redis
    environment:
      REDIS_URL: redis:6379
      SQLITE_DB_PATH: /app/data/titly.db
    volumes:
      - sqlite_data:/app/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: titly-redis-db
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
    driver: local
  sqlite_data:
    driver: local